#!/usr/bin/env node

import { defineCommand, runMain } from 'citty';
import { MCPFirewall } from '@mcp-firewall/core';
import { loadConfig, validateConfig, generateDefaultConfig, FirewallConfigSchema } from '@mcp-firewall/config';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// ─── Main command: run ────────────────────────────────────────

const runCommand = defineCommand({
  meta: {
    name: 'run',
    description: 'Start the MCP Firewall proxy',
  },
  args: {
    config: {
      type: 'positional',
      description: 'Path to config file (YAML or JSON)',
      required: true,
    },
    port: {
      type: 'string',
      description: 'Override HTTP server port',
    },
    'log-level': {
      type: 'string',
      description: 'Log level: debug, info, warn, error',
      default: 'info',
    },
  },
  async run({ args }) {
    const configPath = resolve(args.config);

    console.error(`[mcp-firewall] Loading config from: ${configPath}`);

    try {
      const { config } = loadConfig(configPath);

      // Override port if specified
      if (args.port) {
        config.server.port = parseInt(args.port, 10);
      }

      const firewall = new MCPFirewall({ config, hotReload: true });

      // Handle shutdown signals
      const shutdown = async () => {
        console.error('\n[mcp-firewall] Shutting down...');
        await firewall.stop();
        process.exit(0);
      };

      process.on('SIGINT', shutdown);
      process.on('SIGTERM', shutdown);

      await firewall.start();

      if (config.mode === 'http') {
        console.error(`[mcp-firewall] Ready. Proxy: http://${config.server.host}:${config.server.port}`);
        if (config.observability.metrics.enabled) {
          console.error(`[mcp-firewall] Metrics: http://${config.server.host}:${config.observability.metrics.port}${config.observability.metrics.path}`);
        }
        if (config.dashboard.enabled) {
          console.error(`[mcp-firewall] Dashboard: http://${config.dashboard.host}:${config.dashboard.port}`);
        }
      } else {
        console.error('[mcp-firewall] Stdio proxy ready. Waiting for requests from parent process...');
      }

    } catch (err) {
      console.error('[mcp-firewall] Failed to start:', err instanceof Error ? err.message : err);
      process.exit(1);
    }
  },
});

// ─── Init command ─────────────────────────────────────────────

const YAML_TEMPLATE = `# MCP Firewall Configuration
# Generated by: mcp-firewall init
# Docs: https://github.com/mcp-firewall/mcp-firewall

version: "1"

# Proxy mode: 'stdio' (for Claude Desktop) or 'http' (for team server)
mode: stdio

# Upstream MCP servers to proxy to
upstreams:
  - name: example
    transport: stdio
    command: npx
    args:
      - "-y"
      - "@modelcontextprotocol/server-filesystem"
      - "/tmp"

# ─── Security Policies ────────────────────────────────────────
policies:
  # Block any MCP method not in this list
  method_allowlist:
    enabled: true
    allowed_methods:
      - initialize
      - ping
      - tools/list
      - tools/call
      - resources/list
      - resources/read
      - prompts/list
      - prompts/get
    block_unknown: true

  # Role-Based Access Control (disabled by default)
  rbac:
    enabled: false
    rules: []
    # Example rule:
    # - name: "allow-read-only"
    #   principals:
    #     - type: client-id
    #       pattern: "claude-desktop"
    #   targets:
    #     - method: "tools/call"
    #       toolName: "read_*"
    #   permission: allow

  # Rate Limiting (disabled by default)
  rate_limiting:
    enabled: false
    rules: []
    # Example rule:
    # - name: "per-client-global"
    #   window: "1m"
    #   maxRequests: 100
    #   keyBy: ["client-id"]

  # Parameter Validation
  parameter_validation:
    enabled: true
    strict_mode: false
    max_string_length: 1048576

  # Content Filtering (disabled by default)
  content_filter:
    enabled: false
    rules: []
    # Example rule:
    # - pattern: "rm -rf /"
    #   action: block
    #   phase: input

  # Sensitive Data Detection
  sensitive_data:
    enabled: true
    detectors:
      - type: credit-card
        action: mask
      - type: api-key
        action: mask
      - type: jwt
        action: mask

# ─── Observability ────────────────────────────────────────────
observability:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"

  tracing:
    enabled: false

  audit_log:
    enabled: true
    output: stdout
    format: jsonl

  token_tracking:
    enabled: true
    estimation_mode: conservative

# ─── Database ──────────────────────────────────────────────────
database:
  type: sqlite
  sqlite:
    path: "./data/mcp-firewall.db"

# ─── Dashboard ─────────────────────────────────────────────────
dashboard:
  enabled: true
  host: "127.0.0.1"
  port: 9021
`;

const initCommand = defineCommand({
  meta: {
    name: 'init',
    description: 'Generate a default mcp-firewall.yaml configuration file',
  },
  args: {
    output: {
      type: 'string',
      description: 'Output file path',
      default: 'mcp-firewall.yaml',
    },
    force: {
      type: 'boolean',
      description: 'Overwrite existing file',
      default: false,
    },
  },
  run({ args }) {
    const outputPath = resolve(args.output);

    // Check if file exists
    try {
      readFileSync(outputPath);
      if (!args.force) {
        console.error(`[mcp-firewall] File already exists: ${outputPath}`);
        console.error('[mcp-firewall] Use --force to overwrite.');
        process.exit(1);
      }
    } catch {
      // File doesn't exist, proceed
    }

    writeFileSync(outputPath, YAML_TEMPLATE, 'utf-8');
    console.error(`[mcp-firewall] Generated config: ${outputPath}`);
    console.error('[mcp-firewall] Edit this file to configure your upstream servers and policies.');
    console.error('[mcp-firewall] Then run: mcp-firewall run ' + outputPath);
  },
});

// ─── Validate command ─────────────────────────────────────────

const validateCommand = defineCommand({
  meta: {
    name: 'validate',
    description: 'Validate a firewall configuration file',
  },
  args: {
    config: {
      type: 'positional',
      description: 'Path to config file (YAML or JSON)',
      required: true,
    },
  },
  run({ args }) {
    const configPath = resolve(args.config);

    try {
      const { config } = loadConfig(configPath);
      console.log(`✅ Configuration is valid`);
      console.log(`   Mode: ${config.mode}`);
      console.log(`   Upstreams: ${config.upstreams.length}`);
      for (const u of config.upstreams) {
        console.log(`     - ${u.name} (${u.transport})`);
      }
      console.log(`   Auth: ${config.auth.enabled ? 'enabled' : 'disabled'}`);
      console.log(`   RBAC rules: ${config.policies.rbac.rules.length}`);
      console.log(`   Rate limit rules: ${config.policies.rateLimiting.rules.length}`);
      console.log(`   Metrics: ${config.observability.metrics.enabled ? `port ${config.observability.metrics.port}` : 'disabled'}`);
      console.log(`   Dashboard: ${config.dashboard.enabled ? `port ${config.dashboard.port}` : 'disabled'}`);
    } catch (err) {
      console.error(`❌ Invalid configuration:`);
      if (err instanceof Error) {
        console.error(`   ${err.message}`);
      } else {
        console.error(`   ${String(err)}`);
      }
      process.exit(1);
    }
  },
});

// ─── Dashboard command ────────────────────────────────────────

const dashboardCommand = defineCommand({
  meta: {
    name: 'dashboard',
    description: 'Start the web dashboard only (without the proxy)',
  },
  args: {
    port: {
      type: 'string',
      description: 'Dashboard port',
      default: '9021',
    },
  },
  async run({ args }) {
    console.error(`[mcp-firewall] Dashboard starting on port ${args.port}...`);
    console.error(`[mcp-firewall] Note: Dashboard requires the proxy to be running separately.`);
    console.error(`[mcp-firewall] Dashboard UI will be available in a future release.`);
    // Dashboard server will be implemented in Phase 4
  },
});

// ─── Main entry ───────────────────────────────────────────────

const main = defineCommand({
  meta: {
    name: 'mcp-firewall',
    version: '0.1.0',
    description: 'MCP Firewall — Security & Observability proxy for MCP',
  },
  subCommands: {
    run: runCommand,
    init: initCommand,
    validate: validateCommand,
    dashboard: dashboardCommand,
  },
});

runMain(main);
